DEFAULT_SETTINGS = {
    "MainWindow/start_minimized": True,
    "MainWindow/theme": "default",
    "MainWidget/status_image/size": 28,
    "MessageWidget/image/show": True,
    "MessageWidget/image/size": 33,
    "MessageWidget/font/title": "Noto Sans,17,-1,5,75,0,0,0,0,0,Bold",
    "MessageWidget/font/date": "Noto Sans,11,-1,5,50,1,0,0,0,0,Italic",
    "MessageWidget/font/content": "Noto Sans,11,-1,5,50,0,0,0,0,0,Regular",
    "ApplicationModelItem/icon/show": True,
    "ApplicationModelItem/icon/size": 33,
    "tray/notifications/enabled": True,
    "tray/notifications/priority": 5,
    "tray/show": True,
    "tray/minimize": True,
    "tray/notifications/duration_ms": 5000,
    "tray/notifications/icon/show": True,
}
